# Generated by Django 2.1 on 2019-04-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_code', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='update date')),
                ('trade_price', models.IntegerField(default=0)),
                ('trade_time', models.TimeField(verbose_name='trade time')),
            ],
        ),
        migrations.CreateModel(
            name='StockRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_num', models.IntegerField(default=0)),
                ('corp_name', models.CharField(max_length=200)),
                ('symbol_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.DailyStock')),
            ],
        ),
    ]
