"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bfjlx_!mzv*-6#pg#&erj)-ryu-2p7nc)n2dx7p4w%vc2trsh_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']


# Application definition
# 앱 : 장고 프로젝트에서 동작할 기능들, 사용자들이 사용할 기능
# 미들웨어 : 웹 서버와 장고 애플리케이션 사이에서 동작하는 기능(보안 관련)
INSTALLED_APPS = [
    # 장고 다운받을 때 관리자페이지가 생성되는 이유
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 장고에서는 정적페이지를 serving하진 않지만, 강제적으로 정적파일 실행하도록 해준다.
    # 다이나믹페이지
    'django.contrib.staticfiles',
    'polls.apps.PollsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # 앱을 들어와서 templates 파일들을 먼저 찾는다.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# 데이터베이스 설정
# 1. DB 제품군 설정 : sqlite3, mysql, postgre, oracle
# 2. DBMS 계정정보 : host, dbname, id, password
# 3. Master, Slave 설정 :
# 쓰기 가능한 Master : 1대 ->
# 읽기 전용 Slave : 여러대, 5대
# 클러스터링 : 여러대의 데이터베이스에 대한 동기화 같은 설정이 힘들 때 사용
# AWS : Aurora DB - MySQL, MariaDB (MySQL, MariaDB에선 언제든지 Aurora DB 사용가능)


# 댓수를 늘리는 것 : Out Scaling
# 사용을 높이는 것 : Up Scaling

# 1) 데이터베이스 설정
# 2) DB 초기화
# migrate : 초기화할 때 , DB 변경 사항 적용할 때
# 3) 관리자 계정 생성 : python manage.py createsuperuser
# 3-1) 비밀번호 변경 : python manage.py changepassword [계정명]
# 관리자페이지 -> DB를 사용하기 위한 인터페이스
# 장고 관리자 페이지 -> 개발자를 위한 관리자 페이지
# 초반에는 실무자와 같이 사용 -> 실무자를 위한 관리자페이지 별도 제작


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

